import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav className="flex items-center justify-between p-6 bg-blue-500">
            <div className="text-white">
              <Link href="/" className="mr-4 hover:text-gray-300">
                Home
              </Link>
              <Link href="/users" className="mr-4 hover:text-gray-300">
                Users
              </Link>
              <Link href="/todos" className="hover:text-gray-300">
                Todos
              </Link>
            </div>
          </nav>
        </header>
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  );
}
